type Account {
  firstName: String
  lastName: String
  address: String
  phone: String
  website: String
  company: String
  accountType: String
}

type Balance {
  amount: Float
  currency: String
  lastUpdated: String
}

type AccountBalances {
   id: ID!
  firstName: String
  lastName: String
  accountType: String
  company: String
  address: String
  phone: String
  website: String
  balance: Balance
}


type Transaction {
  accountId: ID!
  date: String
  amount: Float
  transactionType: String
  description: String
}

input TransactionInput {
  accountId: ID!
  date: String!
  amount: Float!
  transactionType: String!
  description: String
}

type DeleteResponse {
  message: String!
}


type Query {
 # Looks for a account by ID
  account(id: ID!): Account
 # Returns the list of all accounts
  accounts: [Account]
  # Returns  accounts by id
  accountBalances(id: ID!): AccountBalances
}

type Mutation {
 # Creates a new transaction
  createTransaction(input: TransactionInput!): DeleteResponse
  deleteTransaction(transactionId: ID!): DeleteResponse
}