schema {
  query: Query
}

type Query {
  account(id: ID!): Account
  balance(id: ID!): Balance
  transaction(id: ID!): Transaction
  accounts: [Account]
  balances: [Balance]
  transactions: [Transaction]
}

type Account {
  firstName: String
  lastName: String
  address: String
  phone: String
  website: String
  company: String
  accountType: String
}

type Balance {
  id: ID
  balanceType: String
  amount: Float
}

type Transaction {
  id: ID
  tranAmount: Float
  description: String
  tranDate: String
}
